import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
	createDb() {
		let workouts = [
			{
				id: 1,
				name: 'Russian Twist',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 2,
				name: 'Plank',
				type: 'static',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 3,
				name: 'Flutter Kicks',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 4,
				name: 'Plank Dips',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 5,
				name: 'V Ups',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 6,
				name: 'Plank Knee to Elbow',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 7,
				name: 'Big Circle',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 8,
				name: 'Superman',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 9,
				name: 'Side Crunch',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 10,
				name: 'Pulse Up',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 11,
				name: 'Hollow Man',
				type: 'static',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 12,
				name: 'Toe to Bar',
				type: 'dynamic',
				location: 'hanging',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 13,
				name: 'Scissor Kick',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 14,
				name: 'Crunch Ball Raise',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 15,
				name: 'Ball Bridge',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 16,
				name: 'Mountain Climber',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 17,
				name: 'Ball Knee Tuck',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 18,
				name: 'Knee In',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 19,
				name: 'Starfish',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 20,
				name: 'Cherry Picker',
				type: 'dynamic',
				location: 'ground',
				typeShow: true,
				locationShow: true,
				selected: false,
			},
			{
				id: 21,
				name: 'Hanging Knee Raise',
				type: 'dynamic',
				location: 'hanging',
				typeShow: true,
				locationShow: true,
				selected: false,
			},

		]; 
		return {workouts};
	}
}

